name: Deploy VitePress site to Liteyuki PaaS

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  statuses: write

concurrency:
  group: pages
  cancel-in-progress: false

env:
  MELI_SITE: f31e3b17-c4ea-4d9d-bdce-9417d67fd30e

jobs:
  # 构建工作
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 如果未启用 lastUpdated，则不需要
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Setup API markdown
        run: |-
          python -m pip install litedoc
          chmod +x build-docs.sh
          ./build-docs.sh

      - name: 安装 pnpm
        uses: pnpm/action-setup@v2
        with:
          run_install: true
          version: 8

      - name: 设置 Node.js
        run: |-
          pnpm install

      - name: 构建文档
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: |-
          pnpm run docs:build


      - name: "发布"
        run: |
          npx -p "@getmeli/cli" meli upload docs/.vitepress/dist \
            --url "https://pages.liteyuki.icu" \
            --site "$MELI_SITE" \
            --token "$MELI_TOKEN" \
            --release "$GITHUB_SHA"
        env:
          MELI_TOKEN: ${{ secrets.MELI_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
